### ISSUE TITLE
BENCHMARKS

### ISSUE THREAD

**Issue by Houdaaithsissine** [DfX-NYUAD/GNNUnlock#4]
Hello, 
I have 2 questions: 
the first one is on how can I try GNNUnlock on only one testbench like AntiSAT_c2670, for example ? 
Is it even possible ? 
the second is where can I find all the result of GNNUnlock on Anti-SAT ?

Thank you

**Comment by lilasrahis** [comment]
Hello,
1) Do you mean to run model inference on a testing circuit after it has been trained? You can check that feature in the GraphSAINT code, i.e., dump the model and then loading it for inference later. As for the GNNUnlock parser, you can convert a single benchmark to a graph. The benchmark should be inside a directory since the parser expects a directory as an input and not a single file.
2) You can find the results in our DATE'21 and TETC'21 papers.

Check Table IV in
https://arxiv.org/pdf/2012.05948.pdf
